[package]
name = "pr-commentator"
version = "0.1.0"
authors = ["tibo <delor.thibault@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
github-types = "0.1.1"
url = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = "2" 